# Generated by Django 3.0.5 on 2020-05-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Station',
            new_name='Gate',
        ),
        migrations.RenameField(
            model_name='gate',
            old_name='station_no',
            new_name='no',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='entry_station',
            new_name='entry_gate',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='exit_station',
            new_name='exit_gate',
        ),
        migrations.RemoveField(
            model_name='log',
            name='entry_image',
        ),
        migrations.RemoveField(
            model_name='log',
            name='exit_image',
        ),
        migrations.RemoveField(
            model_name='log',
            name='fare',
        ),
        migrations.AddField(
            model_name='log',
            name='entry_status',
            field=models.CharField(choices=[('late', 'late'), ('early', 'early'), ('on time', 'on time'), ('in office', 'in office')], default='on time', max_length=100),
        ),
        migrations.AddField(
            model_name='log',
            name='exit_status',
            field=models.CharField(choices=[('late', 'late'), ('early', 'early'), ('on time', 'on time'), ('in office', 'in office')], default='on time', max_length=100),
        ),
    ]
