# Generated by Django 3.0.5 on 2020-05-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200517_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='entry_status',
            field=models.CharField(default='not entered', max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='exit_status',
            field=models.CharField(default='in office', max_length=100),
        ),
    ]
