# Generated by Django 3.0.5 on 2020-05-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200517_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='entry_status',
            field=models.CharField(blank=True, default='not entered', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='exit_status',
            field=models.CharField(blank=True, default='in office', max_length=100, null=True),
        ),
    ]
